### ISSUE TITLE
AttributeError: 'module' object has no attribute 'redirect'

### ISSUE THREAD

**Issue by s-chand** [ViderumGlobal/ckanext-requestdata#17]
Hey guys,
So I am testing this plugin as I am getting the above error with the following traceback whenever I try to create a dataset.

`
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/weberror/evalexception.py', line 429 in respond
  app_iter = self.application(environ, detect_start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/fanstatic/publisher.py', line 234 in __call__
  return request.get_response(self.app)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
  response = request.get_response(self.app)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/lib/ckan/default/src/ckan/ckan/config/middleware/pylons_app.py', line 250 in inner
  result = application(environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/beaker/middleware.py', line 73 in __call__
  return self.app(environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/beaker/middleware.py', line 156 in __call__
  return self.wrap_app(environ, session_start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/routes/middleware.py', line 131 in __call__
  response = self.app(environ, start_response)
File '/usr/lib/ckan/default/src/ckan/ckan/config/middleware/common_middleware.py', line 80 in __call__
  return self.app(environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/wsgiapp.py', line 124 in __call__
  controller = self.resolve(environ, start_response)
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pylons/wsgiapp.py', line 263 in resolve
  return self.find_controller(controller)
File '/usr/lib/ckan/default/src/ckan/ckan/config/environment.py', line 58 in find_controller
  mycontroller = ep.resolve()
File '/usr/lib/ckan/default/local/lib/python2.7/site-packages/pkg_resources/__init__.py', line 2414 in resolve
  module = __import__(self.module_name, fromlist=['__name__'], level=0)
File '/usr/lib/ckan/default/src/ckanext-requestdata/ckanext/requestdata/controllers/package.py', line 15 in <module>
  redirect = base.redirect
AttributeError: 'module' object has no attribute 'redirect'
`

any ideas what I may be doing wrong?

**Comment by s-chand** [comment]
Traceback leads here just in case:
https://github.com/ViderumGlobal/ckanext-requestdata/blob/master/ckanext/requestdata/controllers/package.py#L15

**Comment by klikstermkd** [comment]
In CKAN 2.7, the `redirect` function in the base module is renamed to `redirect_to`.

**Comment by s-chand** [comment]
Yeah. Thanks @klikstermkd 
Any chance that a fix will be released soon?

**Comment by klikstermkd** [comment]
Not sure, because this project is not supported anymore by Viderum.

**Comment by s-chand** [comment]
Ok. No probs. 2 options.

1. I may create a fork and maintain it myself or
2. Create a PR and fix this

What'd you recommend?

**Comment by klikstermkd** [comment]
Create a PR :-)

**Comment by s-chand** [comment]
:)
OK thanks

**Comment by ZoranPandovski** [comment]
@s-chand Just make sure it will work with older versions too.

**Comment by s-chand** [comment]
Sure.

**Comment by newkdukem** [comment]
PR #18 has been merged. This issue will still be open, until we modify the Travis setup

**Comment by s-chand** [comment]
Thanks

**Comment by ZoranPandovski** [comment]
Travis setup is fixed. I will close the issue.
