### ISSUE TITLE
Package not available in PyPi

### ISSUE THREAD

**Issue by tgirgin23** [ViderumGlobal/ckanext-requestdata#21]
I am getting the following error when trying to pip install ckanext-requestdata

`No matching distribution found for ckanext-requestdata`

Current workaround is to build the package yourself using

`python setup.py sdist && python setup.py install`

Thank you for releasing this extension!

**Comment by ZoranPandovski** [comment]
Hi @tgirgin23 , we still haven't submit this extension to PyPi, so you can build the package following https://github.com/ViderumGlobal/ckanext-requestdata#development-installation.

**Comment by tgirgin23** [comment]
@ZoranPandovski Thank you for the quick reply. I was confuse due to the README saying to install pip!
