### ISSUE TITLE
CKAN 2.8 compatibility

### ISSUE THREAD

**Issue by pwalsh** [ViderumGlobal/ckanext-requestdata#23]
Does this extension work with CKAN 2.8, and, if not, what work needs to be done for 2.8 compatibility

**Comment by akariv** [comment]
Looks like it's compatible.

See https://github.com/keitaroinc/ckanext-datagovmk/blob/29b1dbe52524d0a34407cacac8e0a42330a7852c/Dockerfile

**Comment by akariv** [comment]
Not all packages are uploaded into PyPi - I updated the README to reflect that fact.

You can install this package using
`pip install https://github.com/ViderumGlobal/ckanext-requestdata/archive/master.zip`
