### ISSUE TITLE
Path for posting data needs to be changed

### ISSUE THREAD

**Issue by danmihaila** [ViderumGlobal/ckanext-requestdata#4]
The extension is using a standard path in CKAN /dataset/send_request when creating new request data. It needs to be changed to something else.

**Comment by ZoranPandovski** [comment]
Hi Dan. Can you be more specific, what problems you got ? Are you using the same path in one of your extensions ?

**Comment by danmihaila** [comment]
@ZoranPandovski as path /dataset/this-is-my-url is a standard url for datasets in CKAN. it is bad practice to use in an extension the path /dataset/request_data . We faced this problem when we changed the plugins order .

**Comment by danmihaila** [comment]
the path that needs to be changed is "/dataset/send_request" . I updated my previous comments too.

**Comment by ZoranPandovski** [comment]
I will make the change by the e.o.d , after that we will need to make good testing to be sure that everything is working as expected.

**Comment by danmihaila** [comment]
@ZoranPandovski thank you

**Comment by ZoranPandovski** [comment]
@danmihaila I made the required changes. This is a new tag: https://github.com/ViderumGlobal/ckanext-requestdata/releases/tag/v2.1.2. Tomorrow i will deploy on vanilla portal. I

**Comment by danmihaila** [comment]
thank you @ZoranPandovski
